### ISSUE TITLE
Code release time

### ISSUE THREAD

**Issue by Kizuna-AII** [jinkun-hao/ID-Sculpt#1]
Hi, thank you for your excellent work!
Is there an estimated time when the inference code & pre-trained models will be released?

**Comment by jinkun-hao** [comment]
Thanks for your attention. Our work is an optimization-based method, so there are no pre-trained models. The inference code will be released as soon as our work is accepted.

**Comment by epratheeban** [comment]
Hi
Thanks again for the nice paper. Do you have any expected timeline for code release ?
